### ISSUE TITLE
Internal server error in HASS configuration

### ISSUE THREAD

**Issue by wictorwilen** [astrandb/senz_hass#21]
### The problem

Since this morning I get the following error message: 

```
Retrying setup: 500, message='Internal Server Error', url=URL('https://account-link.nabucasa.com/refresh_token/senz')
```

### Version of SENZ WiFi integration having the issue?

0.0.6

### Version of Home Assistant Core having the issue?

2022.4.5

**Comment by astrandb** [comment]
Try to restart Homeassistant. You should then be asked to reauthenticate with the Senz server. If you still get this error it is likely a problem with the authentication server at Raychem/Senz.

**Comment by wictorwilen** [comment]
Restarted Home Assistant a couple of time with no luck.

**Comment by astrandb** [comment]
And no Reauthentication card on Configuration->Integrations??
As a final try, you could try to remove the integration and add it back.
FYI: There is an official integration for Senz in the pipeline for HA 2022.5. When it is released I will most likely stop maintaining this variant.

**Comment by wictorwilen** [comment]
Removing it and adding it back worked. Thanks
