### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by henkkahi** [astrandb/senz_hass#24]
### The problem

I have faced error message: Retrying setup: 500, message='Internal Server Error', url=URL('https://account-link.nabucasa.com/refresh_token/senz'). Connection to thermostats stopped working. 

### Version of SENZ WiFi integration having the issue?

senz-0.0.6

### Version of Home Assistant Core having the issue?

core-2022.10.4

### Anything in the logs that might be useful for us?

```txt
Retrying setup: 500, message='Internal Server Error', url=URL('https://account-link.nabucasa.com/refresh_token/senz')
```

**Comment by astrandb** [comment]
Something has caused a deadlock. It will probably work again if you remove the integration and readd it.
However, this integration is no longer maintained. There is now an official integration built into Home Assistant that is recommended. There are no differnces on the surface but it is maintained properly.
Remove the installation from Settings->Integrations, from configuration.yaml  and then from HACS. Restart HA and add the official Senz integration.
