### ISSUE TITLE
unauthorized_client

### ISSUE THREAD

**Issue by Schlbuditz** [astrandb/senz_hass#9]
### The problem

Followed the instructions, but when I logon to https://id.senzthermostat.nvent.com/ I get this error

"Sorry, there was an error : unauthorized_client"

### Version of SENZ WiFi integration having the issue?

0.0.2

### Version of Home Assistant Core having the issue?

core-2021.12.9

### Additional information

![senz](https://user-images.githubusercontent.com/24764358/149635620-38a56cc1-d4ec-422f-94d8-9ce58e9f5f47.png)

**Comment by astrandb** [comment]
I guess that you first got the login screen from nVent/Raychem, entered your username and password and then got the message message above.

This indicates that something is wrong with the setup.

When applying for credentials from nVent, please make sure that:
- The client mode should be "Authorization mode"
- Redirect url should be the url to HA that you use when adding the integration e.g `http://<local_ip>:8123/auth/external/callback`

**Comment by Schlbuditz** [comment]
User error
